### ISSUE TITLE
Custom Settings.yaml is overriden

### ISSUE THREAD

**Issue by johannessteu** [million12/docker-typo3-flow-neos-abstract#20]
If you define somehting like
```
TYPO3:
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'smtp.mail.com'
```
the host will be overriden with the mysql server ip.

**Comment by svparijs** [comment]
I've had similar issues with using Couchdb regarding the `host: ''` option.

**Comment by ryzy** [comment]
@johannessteu @svparijs 
`host:` part is updated in Settings.yaml by this sed command:
`sed -i -r "1,/host:/s/host: .+?/host: $T3APP_DB_HOST/g" $settings_file`

Which means: take first line with `host:` and replace it with $T3APP_DB_HOST.

The simplest workaround for it is to have `Flow.persistence.backendOptions` at the beginning of your Settings.yaml, then SwiftMailer.

```
TYPO3:
  Flow:
    persistence:
      backendOptions:
        ...
        host: xyz

  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'smtp.mandrillapp.com'

My:
  Package:
    rabbitmq:
      host:     RABBITMQ_HOST
```

And it works. Hope it helps.
